ALTER TABLE WO_MST_NOTARY
ADD STATUS varchar2(100) DEFAULT null;

ALTER TABLE WO_MST_NOTARY
ADD TANGGAL_PENSIUN date DEFAULT null;

ALTER TABLE WO_MST_NOTARY
ADD TANGGAL_BERAKHIR_PKS date DEFAULT null;

ALTER TABLE WO_MST_NOTARY
ADD JENIS_PENGAJUAN varchar2(100) DEFAULT null;
