ALTER TABLE WO_MST_NOTARY ADD LISTING_STATUS varchar2(30) DEFAULT 'Active';
ALTER TABLE WO_MST_NOTARY ADD PENDING_LISTING_STATUS varchar2(30) DEFAULT null;
ALTER TABLE WO_MST_NOTARY ADD CATATAN_KHUSUS varchar2(2000) DEFAULT null;
ALTER TABLE WO_MST_NOTARY ADD CATATAN_KHUSUS_FILE_ID varchar2(200) DEFAULT null;
ALTER TABLE WO_MST_NOTARY ADD CATATAN_KHUSUS_FILE_NAME varchar2(500) DEFAULT null;
ALTER TABLE WO_MST_NOTARY ADD CATATAN_KHUSUS_ROLE varchar2(20) DEFAULT null;
ALTER TABLE WO_MST_NOTARY ADD JENIS_BEFORE_CATATAN varchar2(100) DEFAULT null;

UPDATE WO_MST_NOTARY SET LISTING_STATUS = 'Active' WHERE LISTING_STATUS IS NULL;
