CREATE SEQUENCE wo_mst_notary_document_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE wo_mst_notary_document (
	NOTARY_DOCUMENT_ID NUMBER NOT NULL,
	NOTARY_ID NUMBER,
	ATTACHMENT_TYPE VARCHAR2(1000),
	ATTACHMENT_FILE VARCHAR2(500),
	FILE_ID VARCHAR2(200),
	FILE_SIZE NUMBER,
	ENABLED_FLAG VARCHAR2(1),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(100),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATE_BY VARCHAR2(100),
	DEL_ID NUMBER,
	CONSTRAINT wo_mst_notary_document_pk PRIMARY KEY (NOTARY_DOCUMENT_ID)
);
