CREATE SEQUENCE wo_mst_notary_history_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE wo_mst_notary_history (
	NOTARY_HISTORY_ID NUMBER NOT NULL,
	NOTARY_ID NUMBER,
	STATUS VARCHAR2(200),
	CATATAN_REVISI VARCHAR2(2000),
	JENIS_PENGAJUAN VARCHAR2(100),
	NO_PENGAJUAN VARCHAR2(100),
	ENABLED_FLAG VARCHAR2(1),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(100),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATE_BY VARCHAR2(100),
	DEL_ID NUMBER,
	CONSTRAINT wo_mst_notary_history_pk PRIMARY KEY (NOTARY_HISTORY_ID)
);
