email.host=srv42.niagahoster.com
email.port=465
email.username=noreply@hobbinity.com
email.password=jjq^uhz[=p{p
email.from=noreply@hobbinity.com
email.domain=@hobbinity.com
email.to=h3ndr407@gmail.com

#email.host=smtp.gmail.com
#email.port=587
#email.username=erec.mail22@gmail.com
#email.password=erec123456
#email.from=erec.mail22@gmail.com
#email.domain=@gmail.com
#email.to=h3ndr407@gmail.com
